-- ---------------------------------------------------------------------------
-- 001_initial_schema
--
-- Student request routing: a student submits a written message, an NLP model
-- classifies it, and the resulting ticket is assigned to the responsible
-- university department.
-- ---------------------------------------------------------------------------

-- gen_random_uuid() is built into PostgreSQL 13+; no extension required.

CREATE TYPE user_role      AS ENUM ('STUDENT', 'DEPARTMENT', 'ADMIN');
CREATE TYPE request_status AS ENUM ('NEW', 'IN_REVIEW', 'RESOLVED');
CREATE TYPE contact_state  AS ENUM ('NEW', 'READ', 'RESOLVED');

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Departments — the routing targets
-- ---------------------------------------------------------------------------

-- Seeded with Dekanat, Maliyyə, Kitabxana and İT Dəstək, but nothing in the
-- schema or the model pipeline is limited to four: adding a department is an
-- INSERT plus retraining with labelled examples for it.
CREATE TABLE departments (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name        text NOT NULL UNIQUE,
  slug        text NOT NULL UNIQUE,
  description text NOT NULL DEFAULT '',
  email       text,
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER departments_updated_at BEFORE UPDATE ON departments
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Identity
-- ---------------------------------------------------------------------------

CREATE TABLE users (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email         text      NOT NULL,
  password_hash text      NOT NULL,
  first_name    text      NOT NULL,
  last_name     text      NOT NULL,
  role          user_role NOT NULL DEFAULT 'STUDENT',
  -- Set for DEPARTMENT staff: the department whose queue they may work on.
  department_id uuid REFERENCES departments (id) ON DELETE SET NULL,
  is_active     boolean   NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT users_email_format CHECK (email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  CONSTRAINT users_name_not_blank
    CHECK (length(btrim(first_name)) > 0 AND length(btrim(last_name)) > 0),
  -- A department account without a department could see nothing at all.
  CONSTRAINT users_department_required_for_staff
    CHECK (role <> 'DEPARTMENT' OR department_id IS NOT NULL)
);
CREATE UNIQUE INDEX users_email_key ON users (lower(email));
CREATE INDEX users_role_idx ON users (role);
CREATE INDEX users_department_idx ON users (department_id);
CREATE TRIGGER users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE password_reset_tokens (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token_hash text        NOT NULL UNIQUE,   -- only the SHA-256 of the token is stored
  expires_at timestamptz NOT NULL,
  used_at    timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX password_reset_tokens_user_idx ON password_reset_tokens (user_id);

-- ---------------------------------------------------------------------------
-- Model registry
-- ---------------------------------------------------------------------------

CREATE TABLE ml_models (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name            text NOT NULL,
  version         text NOT NULL UNIQUE,
  algorithm       text NOT NULL,
  feature_version text NOT NULL DEFAULT 'v1',
  dataset_size    integer,
  is_active       boolean NOT NULL DEFAULT false,
  trained_at      timestamptz,
  -- Accuracy / precision / recall / F1 / confusion matrix, exactly as measured
  -- by ml/train.py. Never hand-written.
  metrics         jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes           text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
-- At most one active model at a time.
CREATE UNIQUE INDEX ml_models_single_active ON ml_models (is_active) WHERE is_active;

-- ---------------------------------------------------------------------------
-- Requests (tickets)
-- ---------------------------------------------------------------------------

CREATE TABLE requests (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Human-readable ticket number shown in the UI (#1042).
  ticket_number          bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) UNIQUE,
  user_id                uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  message                text NOT NULL,
  status                 request_status NOT NULL DEFAULT 'NEW',
  -- The department the classifier routed this to. Kept even if a human later
  -- reassigns, because assigned_department_id is what drives the queues.
  assigned_department_id uuid REFERENCES departments (id) ON DELETE SET NULL,
  resolved_at            timestamptz,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT requests_message_not_blank CHECK (length(btrim(message)) >= 5)
);
CREATE INDEX requests_user_created_idx ON requests (user_id, created_at DESC);
CREATE INDEX requests_department_status_idx
  ON requests (assigned_department_id, status, created_at DESC);
CREATE INDEX requests_status_idx ON requests (status);
CREATE TRIGGER requests_updated_at BEFORE UPDATE ON requests
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- One row per classification of a request. A re-classification after
-- retraining adds a row rather than overwriting, so routing stays auditable.
CREATE TABLE request_predictions (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id    uuid NOT NULL REFERENCES requests (id) ON DELETE CASCADE,
  department_id uuid NOT NULL REFERENCES departments (id) ON DELETE CASCADE,
  confidence    numeric(5, 4) NOT NULL,
  model_version text NOT NULL,
  -- Full probability distribution returned by the model, for the result page
  -- and for later analysis.
  probabilities jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT request_predictions_confidence_range CHECK (confidence BETWEEN 0 AND 1)
);
CREATE INDEX request_predictions_request_idx ON request_predictions (request_id, created_at DESC);
CREATE INDEX request_predictions_department_idx ON request_predictions (department_id);
CREATE INDEX request_predictions_model_idx ON request_predictions (model_version);

-- ---------------------------------------------------------------------------
-- Contact messages & audit trail
-- ---------------------------------------------------------------------------

CREATE TABLE contacts (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name       text NOT NULL,
  email      text NOT NULL,
  subject    text NOT NULL,
  message    text NOT NULL,
  status     contact_state NOT NULL DEFAULT 'NEW',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT contacts_email_format CHECK (email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$')
);
CREATE INDEX contacts_status_created_idx ON contacts (status, created_at DESC);

CREATE TABLE audit_logs (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid REFERENCES users (id) ON DELETE SET NULL,
  action      text NOT NULL,
  resource    text NOT NULL,
  resource_id text,
  metadata    jsonb NOT NULL DEFAULT '{}'::jsonb,
  ip_address  text,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_logs_user_created_idx ON audit_logs (user_id, created_at DESC);
CREATE INDEX audit_logs_resource_idx     ON audit_logs (resource, resource_id);
